var res = {
    brick1x1_png : "res/brick1x1.png",
    brick2x1_png : "res/brick2x1.png",
    brick3x1_png : "res/brick3x1.png",
    brick4x1_png : "res/brick4x1.png",
    brick4x2_png : "res/brick4x2.png",
    ground_png : "res/ground.png",
    ground2_png : "res/ground2.png",
    landing_mp3 : "res/BGM/landing.mp3",
    yasei_mp3 : "res/BGM/yasei.mp3",
    title_wav:"res/BGM/title.wav",
    select_mp3:"res/BGM/select.mp3",
    kettei : "res/BGM/kettei.wav",
    pika_wav : "res/BGM/pika.wav",
    rapu_wav : "res/BGM/rapu.wav",
    nage :"res/BGM/nage.wav",
    clear_wav:"res/BGM/clear.wav",
    over_wav:"res/BGM/over.wav",
    ball_png : "res/playerBall.png",
    kusa1: "res/dot/kusa1.png",
    kusa2: "res/dot/kusa2.png",
    jimen: "res/dot/jimen.png",
    mizu: "res/dot/mizu.png",
    mizu2: "res/dot/mizu2.png",
    mori: "res/mori.png",
    ki: "res/dot/ki.png",
    pika: "res/pika.png",
    rapu:"res/rapu.png",
    ballB:"res/ballB.png",
    wind:"res/waku.png",
    lv1:"res/dot/lv1.png",
    lv2:"res/dot/lv2.png",
    haikei:"res/haikei.jpg",
    zukan:"res/zukan.jpg",
    zukan2:"res/zukan2.png",
    gara:"res/gara.jpg",
    waku2:"res/waku2.png",
    icon1:"res/dot/icon1.png",
    icon2:"res/dot/icon2.png",
    icon3:"res/dot/icon3.png",
    map:"res/map.jpg",
    haikei2:"res/haikei2.jpg",
    saku:"res/dot/saku2.png",
    kumo:"res/kumo.png",
    logo:"res/logo.png"

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
